# Generated by Django 6.0.3 on 2026-03-21 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0002_objetomudanza_fotoobjeto'),
        ('personal', '0001_initial'),
        ('reservas', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_digital', models.ImageField(blank=True, null=True, upload_to='firmas/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('cliente_conforme', models.BooleanField(null=True)),
                ('confirmado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'confirmaciones_entrega',
            },
        ),
        migrations.CreateModel(
            name='FotoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='entregas/fotos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='mudanzas.confirmacionentrega')),
            ],
            options={
                'db_table': 'fotos_entrega',
            },
        ),
        migrations.CreateModel(
            name='ServicioMudanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_viajes_predichos', models.IntegerField(blank=True, null=True)),
                ('rf_tiempo_estimado_min', models.IntegerField(blank=True, null=True)),
                ('viajes_reales', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('en_camino', 'En Camino'), ('en_origen', 'En Origen'), ('cargando', 'Cargando'), ('en_ruta', 'En Ruta'), ('en_destino', 'En Destino'), ('descargando', 'Descargando'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='asignado', max_length=20)),
                ('inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fin_real', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('notas_operador', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='servicio', to='reservas.reserva')),
                ('rf_tipo_contenedor_recomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.tipocontenedor')),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='vehiculos.vehiculo')),
            ],
            options={
                'db_table': 'servicios_mudanza',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dano', 'Daño'), ('faltante', 'Faltante'), ('retraso', 'Retraso'), ('accidente', 'Accidente'), ('queja', 'Queja'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='incidencias/%Y/%m/')),
                ('gravedad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('reportada', 'Reportada'), ('en_revision', 'En Revisión'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='reportada', max_length=20)),
                ('resolucion', models.TextField(blank=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('objeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.objetomudanza')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='mudanzas.serviciomudanza')),
            ],
            options={
                'db_table': 'incidencias',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='mudanzas.serviciomudanza')),
            ],
            options={
                'db_table': 'historial_estado_servicio',
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddField(
            model_name='confirmacionentrega',
            name='servicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacion', to='mudanzas.serviciomudanza'),
        ),
        migrations.CreateModel(
            name='CalificacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('calificacion_puntualidad', models.IntegerField(blank=True, null=True)),
                ('calificacion_cuidado', models.IntegerField(blank=True, null=True)),
                ('calificacion_atencion', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='clientes.cliente')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='mudanzas.serviciomudanza')),
            ],
            options={
                'db_table': 'calificaciones_servicio',
            },
        ),
        migrations.CreateModel(
            name='AsignacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_asignado', models.CharField(choices=[('conductor', 'Conductor'), ('cargador_principal', 'Cargador Principal'), ('cargador_apoyo', 'Cargador de Apoyo')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='personal.personal')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='mudanzas.serviciomudanza')),
            ],
            options={
                'db_table': 'asignacion_personal',
                'unique_together': {('servicio', 'personal')},
            },
        ),
    ]
