# Generated by Django 6.0.3 on 2026-03-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudanzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacionentrega',
            name='firma_digital',
        ),
        migrations.AddField(
            model_name='confirmacionentrega',
            name='firma_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/cliente/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='confirmacionentrega',
            name='firma_conductor',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/conductor/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='confirmacionentrega',
            name='cliente_conforme',
            field=models.CharField(blank=True, choices=[('total', 'Conforme Total'), ('parcial', 'Conforme Parcial'), ('ninguna', 'No Conforme')], default='', max_length=10),
        ),
    ]
