# Generated by Django 6.0.3 on 2026-03-21 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('canal', models.CharField(choices=[('push', 'Push'), ('email', 'Email'), ('sms', 'SMS'), ('sistema', 'Sistema')], max_length=20)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('es_leida', models.BooleanField(default=False)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
