# Generated by Django 6.0.3 on 2026-03-21 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_origen', models.TextField()),
                ('direccion_destino', models.TextField()),
                ('fecha_deseada', models.DateField(blank=True, null=True)),
                ('franja_horaria', models.CharField(blank=True, max_length=20)),
                ('volumen_total_m3', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('peso_total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_objetos', models.IntegerField(default=0)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_servicios_extra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_total_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rf_precio_predicho', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rf_confianza_precio', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='borrador', max_length=20)),
                ('valida_hasta', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='servicios.tiposervicio')),
                ('zona_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_destino', to='zonas.zona')),
                ('zona_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_origen', to='zonas.zona')),
            ],
            options={
                'db_table': 'cotizaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales_vinculados', to='cotizaciones.cotizacion')),
                ('servicio_adicional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicioadicional')),
            ],
            options={
                'db_table': 'cotizacion_servicios_adicionales',
                'unique_together': {('cotizacion', 'servicio_adicional')},
            },
        ),
    ]
