# Generated by Django 6.0.3 on 2026-03-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='latitud_destino',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS destino', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='latitud_origen',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS origen', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='longitud_destino',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS destino', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='longitud_origen',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS origen', max_digits=10, null=True),
        ),
    ]
