# Generated by Django 6.0.3 on 2026-03-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_latitud_destino_cotizacion_latitud_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de lo que se desea trasladar'),
        ),
    ]
