# Generated by Django 6.0.3 on 2026-03-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_fix_coordenadas_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='latitud_destino',
            field=models.FloatField(blank=True, help_text='Coordenada GPS destino', null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='latitud_origen',
            field=models.FloatField(blank=True, help_text='Coordenada GPS origen', null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='longitud_destino',
            field=models.FloatField(blank=True, help_text='Coordenada GPS destino', null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='longitud_origen',
            field=models.FloatField(blank=True, help_text='Coordenada GPS origen', null=True),
        ),
    ]
