# Generated by Django 6.0.3 on 2026-03-21 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('clasificacion', 'Clasificación'), ('regresion', 'Regresión')], max_length=20)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('rmse', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('r2_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('features_usadas', models.JSONField()),
                ('hiperparametros', models.JSONField(blank=True, default=dict)),
                ('ruta_modelo', models.CharField(blank=True, max_length=500)),
                ('es_activo', models.BooleanField(default=True)),
                ('entrenado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rf_modelos',
            },
        ),
        migrations.CreateModel(
            name='RFPrediccionDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('demanda_predicha', models.IntegerField()),
                ('confianza', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('demanda_real', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_demanda', to='ia.rfmodelo')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonas.zona')),
            ],
            options={
                'db_table': 'rf_predicciones_demanda',
            },
        ),
        migrations.CreateModel(
            name='RFPrediccionDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vehiculos_necesarios', models.IntegerField()),
                ('personal_necesario', models.IntegerField()),
                ('confianza', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_disponibilidad', to='ia.rfmodelo')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonas.zona')),
            ],
            options={
                'db_table': 'rf_predicciones_disponibilidad',
            },
        ),
    ]
