# Generated by Django 6.0.3 on 2026-03-25 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFRetroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prediccion', models.CharField(choices=[('precio', 'Predicción de Precio'), ('riesgo', 'Clasificación de Riesgo'), ('contenedor', 'Recomendación de Contenedor'), ('tiempo', 'Estimación de Tiempo'), ('viajes', 'Predicción de Viajes'), ('retencion', 'Probabilidad de Retención'), ('demanda', 'Predicción de Demanda')], max_length=20)),
                ('entidad_tipo', models.CharField(max_length=50)),
                ('entidad_id', models.IntegerField()),
                ('features_entrada', models.JSONField(default=dict)),
                ('valor_predicho', models.JSONField()),
                ('valor_real', models.JSONField(blank=True, null=True)),
                ('confianza', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('error_absoluto', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('error_porcentual', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('fue_correcto', models.BooleanField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentaciones', to='ia.rfmodelo')),
            ],
            options={
                'db_table': 'rf_retroalimentaciones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['tipo_prediccion', 'modelo'], name='rf_retroali_tipo_pr_aaaeb1_idx'), models.Index(fields=['entidad_tipo', 'entidad_id'], name='rf_retroali_entidad_7fe0fb_idx')],
            },
        ),
    ]
