# Generated by Django 6.0.3 on 2026-03-21 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('distrito', models.CharField(blank=True, max_length=50)),
                ('latitud_centro', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud_centro', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zonas',
            },
        ),
        migrations.CreateModel(
            name='TarifaDistancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tarifa_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('zona_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_destino', to='zonas.zona')),
                ('zona_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_origen', to='zonas.zona')),
            ],
            options={
                'db_table': 'tarifas_distancia',
                'unique_together': {('zona_origen', 'zona_destino')},
            },
        ),
    ]
