# Generated by Django 6.0.3 on 2026-03-21 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_personal', models.CharField(choices=[('conductor', 'Conductor'), ('cargador', 'Cargador')], max_length=20)),
                ('numero_licencia', models.CharField(blank=True, max_length=30)),
                ('tipo_licencia', models.CharField(blank=True, max_length=10)),
                ('fecha_ingreso', models.DateField()),
                ('salario_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('esta_disponible', models.BooleanField(default=True)),
                ('servicios_completados', models.IntegerField(default=0)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('incidencias_reportadas', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personal',
                'db_table': 'personal',
            },
        ),
    ]
