# Generated by Django 6.0.3 on 2026-03-21 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('volumen_capacidad_m3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peso_capacidad_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('largo_cm', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ancho_cm', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('alto_cm', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tipos_contenedor',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('kilometraje_actual', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_servicio', 'En Servicio'), ('en_mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], default='disponible', max_length=20)),
                ('foto_url', models.URLField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_contenedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='vehiculos.tipocontenedor')),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='MantenimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateField()),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kilometraje_en', models.IntegerField(blank=True, null=True)),
                ('proximo_km', models.IntegerField(blank=True, null=True)),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='vehiculos.vehiculo')),
            ],
            options={
                'db_table': 'mantenimiento_vehiculo',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
