# Generated by Django 6.0.3 on 2026-03-21 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('criterios', models.JSONField(blank=True, default=dict)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'segmentos_cliente',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('residencial', 'Residencial'), ('empresarial', 'Empresarial')], default='residencial', max_length=20)),
                ('nombre_empresa', models.CharField(blank=True, max_length=200)),
                ('nit', models.CharField(blank=True, max_length=30)),
                ('direccion_predeterminada', models.TextField(blank=True)),
                ('preferencia_comunicacion', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('telefono', 'Teléfono')], default='email', max_length=20)),
                ('rf_probabilidad_retencion', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('rf_segmento_predicho', models.CharField(blank=True, max_length=30)),
                ('rf_ultima_prediccion', models.DateTimeField(blank=True, null=True)),
                ('cantidad_mudanzas', models.IntegerField(default=0)),
                ('monto_total_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='AlertaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('seguimiento', 'Seguimiento'), ('reactivacion', 'Reactivación'), ('promocion', 'Promoción'), ('recordatorio', 'Recordatorio')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_programada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='clientes.cliente')),
            ],
            options={
                'db_table': 'alertas_cliente',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='ComunicacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('llamada', 'Llamada'), ('email', 'Email'), ('sms', 'SMS'), ('sistema', 'Sistema')], max_length=20)),
                ('asunto', models.CharField(blank=True, max_length=200)),
                ('contenido', models.TextField()),
                ('direccion', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], default='saliente', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones', to='clientes.cliente')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comunicaciones_cliente',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ClienteSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.segmentocliente')),
            ],
            options={
                'db_table': 'cliente_segmentos',
                'unique_together': {('cliente', 'segmento')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='segmentos',
            field=models.ManyToManyField(blank=True, through='clientes.ClienteSegmento', to='clientes.segmentocliente'),
        ),
    ]
