# Generated by Django 6.0.3 on 2026-03-25 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_crm_w9_comunicacion_canales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion_destino_habitual',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion_origen_habitual',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion_predeterminada',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_mudanza_preferido',
        ),
    ]
