# Generated by Django 6.0.3 on 2026-03-21 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoMudanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('largo_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ancho_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('alto_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fragilidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('rf_nivel_riesgo', models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10)),
                ('rf_probabilidad_dano', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('rf_proteccion_sugerida', models.CharField(blank=True, max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos', to='inventario.categoriaobjeto')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='cotizaciones.cotizacion')),
            ],
            options={
                'db_table': 'objetos_mudanza',
            },
        ),
        migrations.CreateModel(
            name='FotoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='inventario/fotos/%Y/%m/')),
                ('tipo_foto', models.CharField(choices=[('antes_traslado', 'Antes'), ('despues_traslado', 'Después'), ('incidencia', 'Incidencia')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.objetomudanza')),
            ],
            options={
                'db_table': 'fotos_objeto',
            },
        ),
    ]
