# Generated by Django 6.0.3 on 2026-03-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPlanCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_carga', models.IntegerField()),
                ('zona_posicion', models.CharField(blank=True, max_length=30)),
                ('requiere_proteccion', models.BooleanField(default=False)),
                ('instrucciones_especiales', models.TextField(blank=True)),
                ('fue_cargado', models.BooleanField(default=False)),
                ('fue_descargado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'items_plan_carga',
                'ordering': ['orden_carga'],
            },
        ),
        migrations.CreateModel(
            name='PlanCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_viaje', models.IntegerField(default=1)),
                ('volumen_utilizado_m3', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('peso_total_kg', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('porcentaje_ocupacion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('rf_modelo_version', models.CharField(blank=True, max_length=20)),
                ('rf_datos_entrada', models.JSONField(blank=True, default=dict)),
                ('rf_resultado', models.JSONField(blank=True, default=dict)),
                ('instrucciones_generales', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'planes_carga',
            },
        ),
    ]
