# Generated by Django 6.0.3 on 2026-03-21 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carga', '0001_initial'),
        ('inventario', '0002_objetomudanza_fotoobjeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemplancarga',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_carga', to='inventario.objetomudanza'),
        ),
    ]
