# Generated by Django 6.0.3 on 2026-03-21 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carga', '0002_initial'),
        ('mudanzas', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancarga',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_carga', to='mudanzas.serviciomudanza'),
        ),
        migrations.AddField(
            model_name='plancarga',
            name='tipo_contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculos.tipocontenedor'),
        ),
        migrations.AddField(
            model_name='itemplancarga',
            name='plan_carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carga.plancarga'),
        ),
    ]
